# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OCExpoX-Giveaway-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Popover', '~> 1.0.5'
  # Pods for OCExpoX-Giveaway-iOS

end
